### ISSUE TITLE
Purpose of ingress-shaping-is-avail and egress-shaping-is-avail not clear

### ISSUE THREAD

**Issue by michbin** [openBackhaul/macInterface#14]
The _MacInterfaceCapability_ class contains the _ingress-shaping-is-avail_ and _egress-shaping-is-avail_ attributes which do not seem to be related to some configuration. The _MacInterfaceConfiguration_ class does contain neither shaping parameters nor references to shaping profiles.
Are the attributes mentioned above at the right place?

**Comment by openBackhaul** [comment]
MacInterfaceCapability::ingressShapingIsAvail
MacInterfaceCapability::egressShapingIsAvail
are obsolete and shall be removed from the modeling.

**Comment by openBackhaul** [comment]
Corrected in UML and YANG (e.g. MacInterface_1.0.0-tsp.200123.1415+yang.4).
