### ISSUE TITLE
Various spelling errors

### ISSUE THREAD

**Issue by michbin** [openBackhaul/macInterface#21]
Spelling errors:

- `mac-interface-current-problem` should read `mac-interface-current-problems` to be aligned with the other models.

- `mac-interface-historical-peformance` should read `mac-interface-historical-performances.`

- `historical-performace-data` should read `historical-performance-data-list`

**Comment by openBackhaul** [comment]
Corrected in the UML.

**Comment by openBackhaul** [comment]
Found it also corrected in MacInterface_1.0.0-tsp.200123.1415+yang.4.zip .
