### ISSUE TITLE
MacInterfaceStatus: Editorial issues and spelling errors

### ISSUE THREAD

**Issue by michbin** [openBackhaul/macInterface#3]
The Word document contains some editorial issues and spelling errors in the MacInterfaceStatus section:

- _loopbackKindUp_ is referring to "looping back of air interface header".
- _totalFamesInput_ should read _totalFramesOutput_.
-  The description of some snapshot counters refer to "specified VLAN IDs".

**Comment by openBackhaul** [comment]
Corrected. Thanks for commenting.
