### ISSUE TITLE
Frame counters in the MacInterface Performance->Statistics

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/macInterface#33]
According to the RFC2819 a couple of frame counters, which are currently expressed as performance counters, are actually statistic values. Corresponding attributes should be move within the MacInterface modeling.

Proposal:
The following performance values shall be deleted from the MacInterface model:
MacInterfacePerformanceType::framesOf64Byte
MacInterfacePerformanceType::framesOf65To127Byte
MacInterfacePerformanceType::framesOf128To255Byte
MacInterfacePerformanceType::framesOf256To511Byte
MacInterfacePerformanceType::framesOf512To1023Byte
MacInterfacePerformanceType::framesOf1024To1518Byte

The following statistic values shall be created in the MacInterface model:
MacInterfaceStatus::framesOf65To127Byte : INT64 *) = -1
MacInterfaceStatus::framesOf128To255Byte : INT64 = -1
MacInterfaceStatus::framesOf256To511Byte : INT64 = -1
MacInterfaceStatus::framesOf512To1023Byte : INT64 = -1
MacInterfaceStatus::framesOf1024To1518Byte : INT64 = -1

Signed INT64 suffices for counting even the smallest frames on a 10Gbit/s connection for the next 14.975years.

**Comment by openBackhaul** [comment]
Decision at the 5G-xhaul call on Tuesday 2nd of September 2020:

The following performance values shall be deleted from the MacInterface model:
MacInterfacePerformanceType::framesOf64Byte
MacInterfacePerformanceType::framesOf65To127Byte
MacInterfacePerformanceType::framesOf128To255Byte
MacInterfacePerformanceType::framesOf256To511Byte
MacInterfacePerformanceType::framesOf512To1023Byte
MacInterfacePerformanceType::framesOf1024To1518Byte

The following statistic values shall be created in the MacInterface model:
MacInterfaceStatus::framesOf65To127Byte : INT64 = -1
MacInterfaceStatus::framesOf128To255Byte : INT64 = -1
MacInterfaceStatus::framesOf256To511Byte : INT64 = -1
MacInterfaceStatus::framesOf512To1023Byte : INT64 = -1
MacInterfaceStatus::framesOf1024To1518Byte : INT64 = -1

Updating UML and YANG required.

**Comment by demx8as6** [comment]
Correction of the approved list above:
MacInterfaceStatus::framesOf64Byte was missing
We consider it as a bug of the approval and continue with the following list:


The following statistic values shall be created in the MacInterface model:
MacInterfaceStatus::framesOf64Byte
MacInterfaceStatus::framesOf65To127Byte : INT64 = -1
MacInterfaceStatus::framesOf128To255Byte : INT64 = -1
MacInterfaceStatus::framesOf256To511Byte : INT64 = -1
MacInterfaceStatus::framesOf512To1023Byte : INT64 = -1
MacInterfaceStatus::framesOf1024To1518Byte : INT64 = -1

**Comment by openBackhaul** [comment]
Has been solved with MacInterface_1.0.0-tsp.220314.1200.
