### ISSUE TITLE
Removing all elements related to Alarms

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/macInterface#35]
Because Alarms require several objects and many attributes, but provide (almost) no benefit at the MacInterface, it is proposed to delete the following elements from the modeling:
-	MacInterfaceCapability::supportedAlarmList attribute
-	MacInterfaceConfiguration::problemKindSeverityList attribute
-	ProblemKindSeverityType datatype
-	SeverityType enumeration
-	MacInterface_Pac::_macInterfaceCurrentProblems attribute
-	MacInterfaceCurrentProblems class
-	MacInterfaceCurrentProblemType datatype
-	CurrentProblem datatype

**Comment by demx8as6** [comment]
2020-10-21: Agreed as proposed!

**Comment by openBackhaul** [comment]
ProblemNotification deleted, too

**Comment by openBackhaul** [comment]
Has been solved with MacInterface_1.0.0-tsp.220314.1200.
