### ISSUE TITLE
Deleting MacInterfaceConfiguration::performanceMonitoringIsOn

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/macInterface#37]
Despite several device models are supporting performance data at the MacInterface, no device is supporting switching the collection of performance data on/off at the interface level.

It is proposed to delete the attribute.

**Comment by demx8as6** [comment]
2020-10-21: to be check by vendors....
SIAE: RMON counters - if attribute is removed - EthContainer attribute should be used, but dependency between MAC and EC is not transparent. 
Option to be analysed - summary counters moving to a central place.

**Comment by openBackhaul** [comment]
**Decision made at the 5G-xhaul-call on 7th of July 2021**
Delete the MacInterfaceConfiguration::performanceMonitoringIsOn attribute from the model.

**Comment by openBackhaul** [comment]
Has been solved with MacInterface_1.0.0-tsp.220314.1200.
